"""empty message

Revision ID: 08a8a91bf712
Revises: 
Create Date: 2018-04-02 15:02:35.115685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '08a8a91bf712'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading', 'yesterday_consumption')
    op.drop_column('reading', 'pf_l2')
    op.drop_column('reading', 'pf_l3')
    op.drop_column('reading', 'yesterday_saved')
    op.drop_column('reading', 'last_month_consumption')
    op.drop_column('reading', 'pf_l1')
    op.drop_column('reading', 'input_voltage_l2')
    op.drop_column('reading', 'reduction_step')
    op.drop_column('reading', 'temperature_l2')
    op.drop_column('reading', 'temperature_l3')
    op.drop_column('reading', 'software_resets')
    op.drop_column('reading', 'today_consumption')
    op.drop_column('reading', 'input_voltage_l1')
    op.drop_column('reading', 'yearly_consumption')
    op.drop_column('reading', 'cpu_temperature')
    op.drop_column('reading', 'last_year_consumption')
    op.drop_column('reading', 'monthly_consumption')
    op.drop_column('reading', 'output_voltage')
    op.drop_column('reading', 'yearly_saved')
    op.drop_column('reading', 'last_week_consumption')
    op.drop_column('reading', 'current_l3')
    op.drop_column('reading', 'monthly_saved')
    op.drop_column('reading', 'current_l2')
    op.drop_column('reading', 'last_week_saved')
    op.drop_column('reading', 'over_load_indication')
    op.drop_column('reading', 'power_l3')
    op.drop_column('reading', 'weekly_saved')
    op.drop_column('reading', 'over_temperature_indication')
    op.drop_column('reading', 'temperature_l1')
    op.drop_column('reading', 'weekly_consumption')
    op.drop_column('reading', 'window2_consumption')
    op.drop_column('reading', 'device_mode')
    op.drop_column('reading', 'current_l1')
    op.drop_column('reading', 'today_saved')
    op.drop_column('reading', 'last_month_saved')
    op.drop_column('reading', 'power_l1')
    op.drop_column('reading', 'missing_phase_indication')
    op.drop_column('reading', 'last_year_saved')
    op.drop_column('reading', 'power_l2')
    op.drop_column('reading', 'input_voltage_l3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('input_voltage_l3', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('power_l2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('last_year_saved', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('missing_phase_indication', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('power_l1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('last_month_saved', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('today_saved', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('current_l1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('device_mode', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('window2_consumption', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('weekly_consumption', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('temperature_l1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('over_temperature_indication', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('weekly_saved', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('power_l3', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('over_load_indication', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('last_week_saved', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('current_l2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('monthly_saved', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('current_l3', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('last_week_consumption', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('yearly_saved', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('output_voltage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('monthly_consumption', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('last_year_consumption', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('cpu_temperature', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('yearly_consumption', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('input_voltage_l1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('today_consumption', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('software_resets', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('temperature_l3', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('temperature_l2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('reduction_step', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('input_voltage_l2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('pf_l1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('last_month_consumption', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('yesterday_saved', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('pf_l3', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('pf_l2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('reading', sa.Column('yesterday_consumption', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
